# wrangler.toml
name = "kahani"
main = "./.output/server/index.mjs"
assets = { directory = "./.output/public/", binding = "ASSETS" }
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-12-24"